[graph]
all-features = true

[advisories]
git-fetch-with-cli = true

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "OpenSSL",
  "Zlib",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
]
confidence-threshold = 0.9

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

skip = [
  { crate = "windows-sys" },
  { crate = "windows-targets" },
  { crate = "windows_aarch64_gnullvm" },
  { crate = "windows_aarch64_msvc" },
  { crate = "windows_i686_gnu" },
  { crate = "windows_i686_msvc" },
  { crate = "windows_x86_64_gnu" },
  { crate = "windows_x86_64_gnullvm" },
  { crate = "windows_x86_64_msvc" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
